### ISSUE TITLE
Request Entity Too Large 

### ISSUE THREAD

**Issue by Gofannon** [YunoHost-Apps/adminer_ynh#20]
### Describe the bug

Cannot upload a sql file of 2mb to admirer

### Context

- last version of package installed

### Steps to reproduce

- i don't remember exactly the steps to follow

- In the package,
   1. create a new database
   2. import sql file
   3. error shown : **Request Entity Too Large** 
   4. See https://www.cyberciti.biz/faq/linux-unix-bsd-nginx-413-request-entity-too-large/

### Expected behavior

SQL file should be uploaded

### Logs

No logs but workaround keept:

```bash
vim /etc/nginx/conf.d/website.fr.d/adminer.conf

client_max_body_size 5M;
```
Shoud be putted here https://github.com/YunoHost-Apps/adminer_ynh/blob/testing/conf/nginx.conf#L10

I have no idea about the "ideal" value for this...

Maybe, the limit should be decided by the packager itself? With an action panel. As the error is shown direcly to the user and the kind of application should be used by technicals people

**Comment by ericgaspar** [comment]
Fixed with #22
